[package]
name = "sonos"
version = "0.1.2"
authors = ["Jordan Doyle <jordan@9t9t9.com>"]
license = "MIT"
description = "Sonos controller library for.. controlling Sonos"
repository = "https://github.com/w4/sonos.rs"
keywords = ["sonos", "controller", "music"]
readme = "README.md"

[dependencies]
reqwest = "0.8"
log = "0.3"
ssdp = "0.7"
xmltree = "0.6"
error-chain = "0.11"
regex = "0.2"
lazy_static = "0.2"
